name: hf-base-camembert-base

on: 
  workflow_dispatch:

env:
  test_model_name: camembert-base
  test_sku_type: cpu
  test_trigger_next_model: true
  test_queue: test-japaneast-3
  test_set: huggingface-all
  test_keep_looping: false

jobs:
  deploy-model-job:
    runs-on: ubuntu-latest
    steps:
    - name: check-out-repo-step
      uses: actions/checkout@v3
    - name: azure-login-step
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_CRED}}
    - name: pip-install-azure-ai-ml
      run: pip install azure-ai-ml
    - name: pip-install-azureml-core
      run: pip install azureml-core
    - name: pip-install-azureml-mlflow
      run: pip install azureml-mlflow==1.53.0
    - name: pip-install-transformers
      run: pip install transformers==4.34.0
    - name: pip-install-transformers[torch]
      run: pip install transformers[torch]
    - name: pip-install-torchvision
      run: pip install torchvision 
    - name: pip-install-mlflow
      run: pip install mlflow==2.8.0
    - name: pip-install-python-box
      run: pip install python-box 
    - name: pip-install-sacremoses
      run: pip install sacremoses
    - name: pip-install-sentencepiece
      run: pip install sentencepiece
    - name: pip-install-fugashi[unidic-lite]
      run: pip install fugashi[unidic-lite]  
    - name: pip-install-datasets
      run: pip install datasets
    - name: import-evaluate-step
      id: import-evaluate-step
      run: python test_generic_pipeline_automation.py
      working-directory: tests/src/pipeline_component_automation
    - name: deploy-model-step
      id: deploy-model-step
      run: python test_generic_oss_model_deployment.py
      working-directory: tests/src/oss_model_deployment

    - name: trigger-next-model-step
      env:
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      if: ${{ env.test_trigger_next_model == 'true' && steps.deploy-model-step.outputs.NEXT_MODEL != '' && (success() || failure())}}
      run: gh workflow run ${{ steps.deploy-model-step.outputs.NEXT_MODEL }} --ref ${{ github.ref_name }}
