name: Model Status From Logs

on:
  workflow_dispatch

jobs:
  testing:
    runs-on: ubuntu-latest

    env:
      token: ${{ secrets.WORKFLOW_TOKEN }}

    steps:
      - name: check-out-repo-step
        uses: actions/checkout@v3
      - name: azure-login-step
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZ_CRED}}
          # lfs: true
          # repository: Azure/azure-ai-model-catalog
          # branch: main
          # token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r runs_requirements.txt

      - name: Run Python Script
        run: |
          cd tests/src/pipeline_component_automation
          python generic_eval_log.py

      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Attempt to commit changes and handle errors
          set +e
          # git add output_result.csv
          git commit -m "output_result.csv"
          commit_status=$?
          set -e
          
          if [ $commit_status -eq 0 ]; then
            git push origin main
          else
            echo "No changes to commit or there was an error. Skipping commit and push."
          fi
