name: multi-models-deploy

on:
  workflow_dispatch:
    inputs:
      model_list_set1:
        description: 'List of models to deploy (Set 1)'
        required: true
      model_list_set2:
        description: 'List of models to deploy (Set 2)'
      # Add more sets as needed

env:
   test_sku_type: cpu
   test_set: huggingface-all
   test_queue: test-eastus

jobs:
  deploy-model-job:
    runs-on: ubuntu-latest

    steps:
      - name: check-out-repo-step
        uses: actions/checkout@v3

      - name: azure-login-step
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: pip-install-azure-ai-ml
        run: pip install azure-ai-ml

      - name: pip-install-azureml-core
        run: pip install azureml-core

      - name: pip-install-datasets
        run: pip install datasets

      - name: pip-install-azureml-mlflow
        run: pip install azureml-mlflow==1.53.0

      - name: pip-install-transformers
        run: pip install transformers

      - name: pip-install-transformers[torch]
        run: pip install transformers[torch]

      - name: pip-install-torchvision
        run: pip install torchvision

      - name: pip-install-mlflow
        run: pip install mlflow

      - name: pip-install-python-box
        run: pip install python-box 

      - name: pip-install-sacremoses
        run: pip install sacremoses

      - name: pip-install-sentencepiece
        run: pip install sentencepiece

      - name: pip-install-fugashi[unidic-lite]
        run: pip install fugashi[unidic-lite]

      - name: Set Environment Variables
        run: |
          echo "test_model_name=${{ matrix.model }}" >> $GITHUB_ENV

      - name: Deploy Set 1
        if: inputs.model_list_set1
        run: |
          for model in ${{fromJson(inputs.model_list_set1)}}; do
             echo "Deploying $model..."
             cd tests/src/automation_for_constant_library
             python generic_initial_automation_test.py $model
             cd $GITHUB_WORKSPACE  # Reset the working directory
          done
        continue-on-error: true

      - name: Deploy Set 2
        if: inputs.model_list_set2
        run: |
           for model in ${{fromJson(inputs.model_list_set2)}}; do
             echo "Deploying $model..."
             cd tests/src/automation_for_constant_library
             python generic_initial_automation_test.py $model
             cd $GITHUB_WORKSPACE  # Reset the working directory
           done
        continue-on-error: true
