name: runner

on: 
  workflow_dispatch:
   

jobs:
  deploy-model-job:
    runs-on: ubuntu-latest

    steps:
      - name: check-out-repo-step
        uses: actions/checkout@v3

      - name: azure-login-step
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: startrun
        run: echo "Im in runner"

      
         
      
