name: runner

on:
 workflow_dispatch:

 jobs:
  deploy-model-job:
    runs-on: ubuntu-latest
    steps:
    - name: check-out-repo-step
      uses: actions/checkout@v3
    - name: startrun
      run: |
       echo "I am in runner.yml"
   # call-workflow-in-local-repo:
   # uses: ./.github/workflows/MLFlow-bert-base-cased.yml
