name: runner

on:
 workflow_dispatch:

 jobs:
  deploy-model-job:
    runs-on: ubuntu-latest

    steps:
      - name: check-out-repo-step
        uses: actions/checkout@v3

      - name: azure-login-step
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: set-model-env-variable
        run: echo "test_model_name
      
   # call-workflow-in-local-repo:
   # uses: ./.github/workflows/MLFlow-bert-base-cased.yml
