name: Trigger Workflow

on:
 workflow_dispatch:

jobs:
 
   call-workflow-in-local-repo:
    uses: ./.github/workflows/runner.yml
   call-workflow-using-branch:
    uses: ./.github/workflows/runner1.yml
