name: Trigger Workflow

on:
 workflow_dispatch:

 jobs:
 
   call-workflow-in-local-repo:
    uses: ./.github/workflows/runner.yml
   # call-workflow-in-local-repo:
   # uses: ./.github/workflows/MLFlow-bert-base-cased.yml
